### PR TITLE
use fast json serializer

### PR DESCRIPTION
**Pull request by ThomasSevestre**

### CODE REVIEW

**Comment by kpheasey** [comment]
@ThomasSevestre Is there a positive performance impact from doing this?  

It seems odd that the original author would choose the slower ActiveSupport serializer over their faster custom serializer, especially given the overall goal of performance.  That being said, we have already merged in some great performance enhancing contributions and this could be another one.

**Comment by stas** [comment]
@kpheasey I can see why moving away from ActiveSupport makes sense, but in the same time @ThomasSevestre we should keep the JSON encoder pluggable (hence the use of AS here probably), as other gems like OJ, self-register to provide the JSON-encoding support.

So the bigger question here is if we should consider the introduction of a configuration/setup API for the JSON encoder?!

**Comment by ThomasSevestre** [comment]
I've made some tests, I'll give more information asap.

I beleive JSON encoder should be configuration. In my opinion, the multi json trick is too complicated.

**Comment by ThomasSevestre** [comment]
Here is my test script (I'm using active_support 4.2)

    require 'fast_jsonapi'
    require 'oj'
    
    class Simple
      attr_accessor :id, :a0, :a1, :a2, :a3, :a4, :a5, :a6, :a7, :a8, :a9
    end
    class SimpleSerializer
      include FastJsonapi::ObjectSerializer
    
      set_type :my_object
      attributes :a0, :a1, :a2, :a3, :a4, :a5, :a6, :a7, :a8, :a9
    end
    
    module FastJsonapi
      module SerializationCore
        class_methods do
          # bypass multi json...
          def to_json(payload)
            ::ActiveSupport::JSON.encode(payload) if payload.present?
            # ::Oj.dump(payload, mode: :compat, time_format: :ruby, use_to_json: true) if payload.present?
          end
        end
      end
    end
    
    o= Simple.new
    start= Time.now
    100000.times do
      SimpleSerializer.new(o).serialized_json
    end
    puts "simple: #{Time.now - start}\n\n"
    
    Oj.optimize_rails
    
    start= Time.now
    100000.times do
      SimpleSerializer.new(o).serialized_json
    end
    puts "optimized: #{Time.now - start}\n\n"

Results :
- `ActiveSupport::JSON.encode` : 8.45579
- `ActiveSupport::JSON.encode` + `Oj.optimize_rails` : 1.589756
- `Oj.dump` : 8.482486
- `Oj.dump` + `Oj.optimize_rails` : 1.638134

`Oj.optimize_rails` is improving performance a lot
be carrefull, it can break things (I've seen it in other JSON API)

**Comment by stas** [comment]
Alright, as long as we can plug our encoder, I'm onboard with this change.

We use `oj` with the following settings:
```
require 'oj'

Oj.optimize_rails()

Oj.default_options = {
  bigdecimal_as_decimal: true,
  # use_as_json: true,
  # use_to_hash: true,
  # use_to_json: true
}

# Disable encoding of HTML entities in JSON.
ActiveSupport.escape_html_entities_in_json = false
```

The last one seems to no longer be relevant if we skip the AS parts.

Before merging this, if we are all on the same page here, let's update the readme with this little feature :upside_down_face: 

Thank you @ThomasSevestre!

**Comment by ThomasSevestre** [comment]
It's also possible to remove multijson completly, stick with `ActiveSupport::JSON.encode` and promote (enforce ?) `Oj.optimize_rails`

**Comment by jopotts** [comment]
I'm also definitely in favour of this as a pluggable option.

Without it, there's a need to set `ActiveSupport.escape_html_entities_in_json = false` (a global Rails option) to get fast_jsonapi encoding `&` correctly in links. Like in @stas's settings above. Thanks @ThomasSevestre !

**Comment by kpheasey** [comment]
@jopotts @stas I don't really have a strong opinion on this.  So, don't wait on me to handle this.

**Comment by stas** [comment]
I'm onboard with moving this forward. Let's just make sure we mention this in the readme/docs.

**Comment by stas** [comment]
@ThomasSevestre apologies for the late reply! Could you please rebase this PR so that we can merge it. Thank you in advance!

**Comment by ThomasSevestre** [comment]
IMO the best solution is :
- to remove multijson completely (unused in current branches)
- promote `Oj.optimize_rails` in the readme

It gives similar performance than pure Oj implementation (test above)
It removes unreadable code from this gem (multijson)
I beleive Oj is not going to drop rails encoding support anytime soon...

@stas, @jopotts , what do you think?

**Comment by stas** [comment]
@ThomasSevestre I'm not sure I follow. What exactly is this `multi_to_json` ?!

As for the rest, the scope of our work is to provide a stable API to allow folks benefit from the its flexibility. At most we can document and suggest to implement their own JSON serializer using the new `#to_json` public method, which is a fair argument. As for the `oj` and the other alternatives to the standard `json`, I don't think it should be our main concern.

The removal of `ActiveSupport` is ideal, but it's a long-term goal.

Please let me know if you're interested in documenting this new functionality. If not we can merge it and follow-up with another PR to provide the documentation.

**Comment by ThomasSevestre** [comment]
multi_to_json.rb is an unused file in this repo. This PR restore the usage of multi_to_json.rb

I though it was a good idea but as shown above, using multi_to_json.rb with Oj does not improve performance. The only way I found to improve performance is to call `Oj.optimize_rails`

Feel free to merge or close...

**Comment by christophersansone** [comment]
Late to the party here, but I'm wondering.  For those who believe the JSON library should be pluggable, can you offer your reasoning?  If we know that there is a "right" library to use and a "right" configuration to optimize performance, why not just use it?

Making the JSON library pluggable comes with a significant tradeoff: it's up to the developer to choose and configure properly.  If they choose something other than `oj`, or have not chosen anything and are just using their application defaults, then they will most likely have worse performance.  Also, according to @ThomasSevestre's benchmarks above, even if you are using `oj`, it may not be optimally configured.  Apparently the application developer should be calling `Oj.optimize_rails` somewhere in their initialization.  But then what about someone who isn't using Rails?  And what else does this global configuration setting do across the entire application?

Knowing what I know today, I am of the opinion that we should consider going in the opposite direction: choose a single JSON implementation specifically for this library, optimize the configuration for this library, and keep the configuration isolated to this library so that it does not affect other parts of the application.  That said, what if we simply included `oj` in the gemspec and just called `Oj.dump` with the ideal configuration options?  If needed, we can expose the ability to override the configuration options.

Lastly, if the consensus is that there are good reasons to offer pluggable support, can we consider baking a properly configured `oj` implementation as the default, and then letting them opt into a different implementation, e.g. `set_encoder :active_support`?

**Comment by stas** [comment]
@christophersansone we're all on the same page here. In fact `to_json` seems like an internal Netflix shortcut. It's not documented nor encouraged as a public API.

The goal of this PR was to review and come up with a consistent and solid public API to achieve what you've been describing: pluggable JSON serialization.

I still think we need to get rid of that `multi_to_json.rb` file, it's not the goal of this project to do that, we should just let folks hook their implementation through a public API we want to maintain.

**Comment by christophersansone** [comment]
@stas Agreed on all accounts!  Let's remove `multi_to_json.rb`, document that [to_json](https://github.com/fast-jsonapi/fast_jsonapi/blob/c305b699a970ba60e77ba5d7d1f962390bcdc363/lib/fast_jsonapi/serialization_core.rb#L100) can be overridden to customize the hash-to-string conversion, and ensure that any attempts in the library to convert to string (i.e. [serialized_json](https://github.com/fast-jsonapi/fast_jsonapi/blob/c305b699a970ba60e77ba5d7d1f962390bcdc363/lib/fast_jsonapi/object_serializer.rb#L75)) occur through `to_json`.  I think that solves the need to offer the pluggable API.  Does that sound like a plan?

If so, then we just need to decide what the default implementation of `to_json` should be.  Would you want to decide that as part of this PR, or should we just go with the current ActiveSupport implementation for this PR and then consider changing it as a separate PR?

(Just to offer a data point here... I always add `oj` to my Gemfile and assumed that it was being used, until I reviewed this issue and discovered it was not being used in any of my projects! 🤦‍♂   My preference would be to simply let developers `gem install fast_jsonapi` and get the fastest / best serialization out of the box.)

**Comment by stas** [comment]
> If so, then we just need to decide what the default implementation of `to_json` should be. Would you want to decide that as part of this PR, or should we just go with the current ActiveSupport implementation for this PR and then consider changing it as a separate PR?

I think we should stick to the built-in solution, in fact, calling `super()` should be enough, since a modern version of ruby already provides that as part of the standard library.

**Comment by christophersansone** [comment]
@stas That's a great point that the simplest approach is:

```ruby
require 'json'
...
def to_json(payload)
  payload.to_json
end
```

And we can let the developer decide what to do from there.

My only hesitation is that my understanding is that the built in Ruby module is SLOW.  Because this library is called `fast_jsonapi`, it seems expected that the library would optimize for this automatically.

Here is a [nice recent article](https://buttercms.com/blog/json-serialization-in-rails-a-complete-guide) I found on the subject.  In his benchmark, Oj was 5x faster than the standard library.  To me, that's hard to ignore.  Incidentally, this article specifically mentions `multi_to_json.rb` towards the end, and that because Oj is already shipped with `fast_jsonapi`, it is used by default.  That was the case until [this commit](https://github.com/Netflix/fast_jsonapi/commit/5a70b1a686d6e7c103030be02baf81c27fb01417).  So I think now people are not getting the performance they thought they were.  I imagine that's what happened to me: I thought that having `oj` was good enough, and it was... until it wasn't.

I did a little history tracking to try to understand why the change away from `multi_to_json` occurred.  The change occurred in [this PR](https://github.com/Netflix/fast_jsonapi/pull/312), which was specifically to simply remove the dependency on [ActiveSupport core extensions](https://edgeguides.rubyonrails.org/active_support_core_extensions.html#json-support) due to its incompatibility with other gems.  Based on the PR description and code, it looks like the move away from `multi_to_json` was _inadvertent_: the author thought that `ActiveSupport::JSON` was being used by `to_json`, when it was not.

Incidentally, [this PR](https://github.com/Netflix/fast_jsonapi/pull/374) is from someone who happened to notice the performance difference and asked to revert it, but the maintainers became inactive by then.

Therefore, my understanding is that the original intent of the library was to automatically choose the best / fastest parser available, and it used `multi_to_json` to accomplish this.  Its number one preference was to use Oj if available, and then walk down the list of parsers until it eventually got to `Object.to_json`.  It even [presents a log warning if there is no parser other than Object.to_json](https://github.com/fast-jsonapi/fast_jsonapi/blob/c305b699a970ba60e77ba5d7d1f962390bcdc363/lib/fast_jsonapi/multi_to_json.rb#L75), presumably because of the performance problems.

All this said, I would still strongly advocate to offer the best performance by default, by including `oj` (which it already is) and using it as the default `to_json` implementation.  We should probably review the [Oj parameters specified in multi_to_json](https://github.com/fast-jsonapi/fast_jsonapi/blob/c305b699a970ba60e77ba5d7d1f962390bcdc363/lib/fast_jsonapi/multi_to_json.rb#L58) as the default parameters.  We don't need `multi_to_json` anymore, and we don't need 10 different options.  Just one super performant implementation by default, with the ability to easily override it as needed.

@stas If you still feel strongly that we should use `Object.to_json` by default, then we at least need some strong documentation in the README to communicate to the developers that they should configure it for optimized performance.

**Comment by stas** [comment]
@christophersansone I think these are two separate concerns, `oj` as much as other gems, have configurations which we can not assume are good defaults for everyone, that's not the goal of this project either. This project is about providing a library that will be fast, and if that means for somebody swapping `json` with `oj`, that's up to them.

More technically, `oj` is not a pure-ruby implementation, so making it a dependency might complicate some folks life. I think we're all on the same page here, let's ship what we agree upon first :upside_down_face:

**Comment by christophersansone** [comment]
@stas Sounds good!  You're right, I imagine `oj` does not run on JRuby.

One more question, then I promise I'll stop! :smile:  My understanding of your last comment is that you believe that the "model to hash" and "hash to JSON string" are two separate concerns, and that this library should be focused on the "model to hash" implementation and performance, and not concern itself with the "hash to JSON string" conversion.  Is that accurate?

If that's the case, then my concern is that _by having a `to_json` method in the API, we are communicating that it **is** a concern of this library, when it is actually not._ . And now it's up to us to educate them that they will probably want to override `to_json`, which library to choose, etc.

That said, how would you feel about deprecating the "hash to JSON string" conversion all together?  By deprecating (and eventually removing) `to_json` and `serialized_json`, the API would then communicate that this library's job is to convert the model to a hash, and it's up to the developer to figure out the next step.  We can still offer some information on the topic in the README, but at that point we can just link to some generic JSON conversion resources for Ruby / Rails.  We can still implement what we discussed above as the revised `to_json` implementation, but also include a deprecation warning.

My opinion is that we should be totally in or totally out of this part of the process, and it should be reflected in the API.  If we are anywhere in between, then we are giving developers the wrong impression by default.

**Comment by stas** [comment]
@christophersansone that's a great point! I agree that we should take a step back and just leave it totally to the end-user to handle the _hash-to-json_ serialization. Finally they can even implement their own `serialized_json` method as part of the base serializer class.

**Comment by stas** [comment]
@ThomasSevestre I'm closing this in favor of #44 

Thanks again for the contribution!

**Pull request closed without merging**
