### PR TITLE
Add params to set_id block

### PR DESCRIPTION
**Pull request by henvo**
Hey thanks for creating this repo and keeping fast_jsonapi alive

---

A previous pull request added a block to the ObjectSerializer.set_id class
method, which allows passing a block to the set_id method. Currently
this block takes only one argument `record`:
```
set_id do |record|
  "#{record.name.downcase}-#{record.id}"
end
```
This PR adds another argument params to the block:

```
set id do |record, params|
  params[:admin] ?  record.id : "#{record.name.downcase}-#{record.id}"
end
```
This customization can be useful in situation where we serve different
clients that may need different IDs. One nice side effect is also that
the set_id method has the same method signature as the attribute
method.

This PR was copied from https://github.com/Netflix/fast_jsonapi/pull/380

### CODE REVIEW

**Comment by stas** [comment]
@henvo thank you for the PR. This seems like a breaking change. @jopotts @kpheasey what do you think, should we consider the merge for this release?

**Comment by kpheasey** [comment]
@stas This looks good to me.  Can you explain why this is a breaking change.

The optional second `params` argument continues a convention and extends functionality w/o sacrificing performance.  I actually had a similar use case a month ago and it would have been helpful.  We got around it by setting a current user on the model and then referencing it from there, which is not ideal.

**Comment by stas** [comment]
@henvo @kpheasey apologies, I missed the part where the `params` is optional.

**Comment by kpheasey** [comment]
@henvo Can you update this PR to merge into the dev branch?

**Comment by kpheasey** [comment]
@henvo I updated the PR to merge into the dev branch.  Can you resolve the conflicts?

**Comment by henvo** [comment]
Hey all thanks for the feedback. I fixed the merge conflicts.

**Pull request merged**
