### PR TITLE
Fix relationships with &:proc shorthands

### PR DESCRIPTION
**Pull request by attilahorvath**
## What is the current behavior?

If a define a relationship with a `&:proc` shorthand, such as:

```ruby
class MovieSerializer
  include FastJsonapi::ObjectSerializer

  has_many :stars, &:actors
end
```

The serialization fails with `ArgumentError: wrong number of arguments (given 1, expected 0)`.

However, the same thing would have worked as expected had I used a full `do .. end` block here.

## What is the new behavior?

This change fixes this behavior by doing the same arity check as it's been done already for attributes in [Scalar](https://github.com/fast-jsonapi/fast_jsonapi/blob/master/lib/fast_jsonapi/scalar.rb#L14).

It would be nice to extract this bit of code somewhere instead of being duplicated here but I couldn't really find a nice place for that as they don't share a common superclass or anything like that. I can refactor this if anyone has a better idea.

## Checklist

Please make sure the following requirements are complete:

- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes /
  features)
- [X] All automated checks pass (CI/CD)

### CODE REVIEW

**Comment by stas** [comment]
@attilahorvath apologies for a bit of delay in reviewing this...

Before we merge this, I'd like us to review all the parts where we work with procs and use the new internal API method you suggested `call_object_block()`. Based on the #59 it's clear that all these can leverage the same API call.

Functionality aside, let's document this method properly and remove extra tests from #59 once we update it to use this API call. I'm ok if you want to merge this one first and update the #59 later. Let me know what you think...

Thanks in advance! :bowing_man:

**Comment by attilahorvath** [comment]
Hi @stas, thank you for the review.

I think it makes sense to merge this one first and then I'll update #59 to use this method.

**Comment by stas** [comment]
Sounds good.

@attilahorvath may I ask you to provide the docstrings for the new method, consider using the [YARD](https://www.rubydoc.info/gems/yard/file/docs/GettingStarted.md) format.

I'll merge it as soon as you do that. Thanks!

**Comment by attilahorvath** [comment]
Okay, I've given it some more thought and came up with the following.

I have a small helper method that works with either `proc` or `lambda` style code blocks and makes sure to only pass as many parameters as they can take, even if they have default parameters defined (passing more parameters than a lambda could take was the root of all these issues).

This method will be needed in multiple source files so I put it in a new `helpers.rb` file which can be useful later for similar methods that can be used project-wide.

If you're happy with this, I'll update all other usages of proc calls across the gem to use this method so they won't have similar issues in the future.

**Comment by stas** [comment]
@attilahorvath this looks good, let's move forward with this if you have time! :bowing_man:

**Comment by attilahorvath** [comment]
@stas If you're okay with this, then I think we could merge this branch and then I'll update #59 to use this method.

Or should I push all the updates in this branch and close the other PR?

**Comment by stas** [comment]
:bowing_man: @attilahorvath

**Pull request merged**
