### PR TITLE
Sans benchmarks

### PR DESCRIPTION
**Pull request by stas**
## What is the current behavior?

The performance tests have been failing for a while and I disabled them. Reviewing the way the benchmarking was done, I found it pretty hard to maintain and not very relevant (at least at making it part of the tests runtime).

## What is the new behavior?

I setup a separate benchmarking/comparisons project to solve this problem. It's available at:
https://github.com/fast-jsonapi/comparisons

With this opportunity, we can start cleaning the tests and help with #33 where we have a predefined set of dummy data and serializers we reuse across all the test suite.

Added also the coverage support and removed any dead code I could find.

## Example performance output

```
Warming up --------------------------------------
                     fast_jsonapi    57.818k i/s -     62.352k times in 1.078419s (17.30μs/i)
               fast_jsonapi(many)     71.800 i/s -      80.000 times in 1.114201s (13.93ms/i)
            fast_jsonapi(include)     21.412 i/s -      24.000 times in 1.120887s (46.70ms/i)
         active_model_serializers     1.492k i/s -      1.620k times in 1.085847s (670.28μs/i)
   active_model_serializers(many)      1.709 i/s -       2.000 times in 1.170138s (585.07ms/i)
active_model_serializers(include)      0.784 i/s -       1.000 times in 1.275792s (1.28s/i)
             jsonapi-serializable    18.884k i/s -     19.899k times in 1.053758s (52.96μs/i)
       jsonapi-serializable(many)     20.678 i/s -      22.000 times in 1.063927s (48.36ms/i)
    jsonapi-serializable(include)      4.741 i/s -       5.000 times in 1.054731s (210.95ms/i)
              jsonapi-serializers    22.150k i/s -     23.049k times in 1.040592s (45.15μs/i)
        jsonapi-serializers(many)     27.941 i/s -      30.000 times in 1.073695s (35.79ms/i)
     jsonapi-serializers(include)      5.598 i/s -       6.000 times in 1.071828s (178.64ms/i)
Calculating -------------------------------------
                     fast_jsonapi    57.931k i/s -    173.453k times in 2.994156s (17.26μs/i)
               fast_jsonapi(many)     73.792 i/s -     215.000 times in 2.913614s (13.55ms/i)
            fast_jsonapi(include)     20.770 i/s -      64.000 times in 3.081299s (48.15ms/i)
         active_model_serializers     1.510k i/s -      4.475k times in 2.963313s (662.19μs/i)
   active_model_serializers(many)      1.714 i/s -       5.000 times in 2.917981s (583.60ms/i)
active_model_serializers(include)      0.783 i/s -       2.000 times in 2.553811s (1.28s/i)
             jsonapi-serializable    18.930k i/s -     56.651k times in 2.992593s (52.83μs/i)
       jsonapi-serializable(many)     22.528 i/s -      62.000 times in 2.752131s (44.39ms/i)
    jsonapi-serializable(include)      6.182 i/s -      14.000 times in 2.264517s (161.75ms/i)
              jsonapi-serializers    23.071k i/s -     66.449k times in 2.880215s (43.34μs/i)
        jsonapi-serializers(many)     27.701 i/s -      83.000 times in 2.996306s (36.10ms/i)
     jsonapi-serializers(include)      5.870 i/s -      16.000 times in 2.725619s (170.35ms/i)

Comparison:
                     fast_jsonapi:     57930.5 i/s 
              jsonapi-serializers:     23070.8 i/s - 2.51x  slower
             jsonapi-serializable:     18930.4 i/s - 3.06x  slower
         active_model_serializers:      1510.1 i/s - 38.36x  slower
               fast_jsonapi(many):        73.8 i/s - 785.06x  slower
        jsonapi-serializers(many):        27.7 i/s - 2091.30x  slower
       jsonapi-serializable(many):        22.5 i/s - 2571.49x  slower
            fast_jsonapi(include):        20.8 i/s - 2789.08x  slower
    jsonapi-serializable(include):         6.2 i/s - 9370.33x  slower
     jsonapi-serializers(include):         5.9 i/s - 9868.53x  slower
   active_model_serializers(many):         1.7 i/s - 33808.02x  slower
active_model_serializers(include):         0.8 i/s - 73971.79x  slower
```

## Checklist

Please make sure the following requirements are complete:

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been reviewed and added / updated if needed (for bug fixes /
  features)
- [x] All automated checks pass (CI/CD)

### CODE REVIEW

**Comment by christophersansone** [comment]
@stas I think the performance output looks great!  My only concern is that the current implementation would not be easy to test the performance of a change while you're developing it.  The perf utility is currently loading the library from the `Gemfile`, which is pointing to the master branch here.  With the current default implementation, the the only way it could be tested is after it had already been merged.

The old tests were for sure in need of improvement, but I personally liked how I could quickly test the performance of a change without needing to commit / push / merge anything.  Is there a way that this perf tool can work on unmerged branches and possibly even uncommitted code?

Also, I think it would be great if we require the PR creator to include the perf results for any PR that may affect performance.  It would be great for the reviewers to quickly see at a glance how the PR affects performance.

**Comment by stas** [comment]
Thanks @christophersansone! I agree with you that having the perf specs included in the CI process is ideal. But I'd like to do it step by step. In short, I'm planning to integrate them into our CI process, but I see no reasons why those should live in the same repository (maintenance-wise and just generally based on the footprint of the deps/build-time).

**Comment by christophersansone** [comment]
Sweet, well if at all possible in the meantime, offering instructions to run it on a local copy or dev branch would be super helpful.

One idea would be to simply create a rake task to execute the benchmarks, with the ability to specify a file path to the library as a parameter.  If not specified, it could default to the bundled version.  Then maybe the first line of `comparisons/fast_jsonapi.rb` would change to something like:

```ruby
if ENV['FAST_JSONAPI_PATH']
  require ENV['FAST_JSONAPI_PATH']
else
  require 'fast_jsonapi'
end
```

**Comment by stas** [comment]
Sounds good. As I mentioned in the #74, I'd like to merge this only after we do a release of what we currently have. I plan to remove a bunch of code and get the v2.0 with a cleaner and easier to maintain codebase...

**Comment by christophersansone** [comment]
Awesome, is there an issue to track v2.0?  I think there are a few open ended items we are considering to change / deprecate (e.g. allowing the user to specify both `polymorphic` and `serializer` on a relationship).  It would be great to solidify the v2.0 API changes and other breaking changes so that we can implement the migration paths through deprecation warnings and presumably a changelog listing the breaking changes.

**Comment by stas** [comment]
I think shaving off the `key`, `type` and ` record_type` (#34) to delegate if fully to the serializer... Along with the findings from removing 3k lines of code in #74, I'd add #39 and consolidate all the #66 and #23 related API calls, #45 and finally #42. 

Honestly I think we can shave another 200 sloc easily by DRYing things a bit...

**Pull request merged**
